version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - REPOSITORY_URI=821383200340.dkr.ecr.eu-west-1.amazonaws.com/konttiproggis
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t 821383200340.dkr.ecr.eu-west-1.amazonaws.com/konttiproggis:latest .
      - docker tag 821383200340.dkr.ecr.eu-west-1.amazonaws.com/konttiproggis:latest 821383200340.dkr.ecr.eu-west-1.amazonaws.com/konttiproggis:tagi
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push 821383200340.dkr.ecr.eu-west-1.amazonaws.com/konttiproggis:latest
      - docker push 821383200340.dkr.ecr.eu-west-1.amazonaws.com/konttiproggis:tagi
artifacts:
  files:
    - imageDetail.json