AWSTemplateFormatVersion: "2010-09-09"
Description: Creates a DynamoDb Table

Parameters:
  #  Using default VPC and subnets in eu-west-1
  VPC:
    Type: String
    Default: vpc-a39f61da
  SubnetA:
    Type: String
    Default: subnet-0d414ad4c89f96049
  SubnetB:
    Type: String
    Default: subnet-b65421ec
  TaskRoleForTaskDefinition:
    Type: String
    Default: arn:aws:iam::821383200340:role/Konttiproggis-task-role
  TaskExecutionRoleForTaskDefinition:
    Type: String
    Default: arn:aws:iam::821383200340:role/ecsTaskExecutionRole
  DockerImage:
    Type: String
    # Docker image located in ECR
    Default: 821383200340.dkr.ecr.eu-west-1.amazonaws.com/konttiproggis:latest
  ContainerPort:
    Type: Number
    Default: 5000
  ServiceName:
    Type: String
    Default: Konttiproggis-service

Resources:
#  StudentTable:
#    Type: AWS::DynamoDB::Table
#    Properties:
#      AttributeDefinitions:
#        - AttributeName: id
#          AttributeType: S
#        - AttributeName: student_name
#          AttributeType: S
#      KeySchema:
#        - AttributeName: id
#          KeyType: HASH
#        - AttributeName: student_name
#          KeyType: RANGE
#      ProvisionedThroughput:
#        ReadCapacityUnits: "1"
#        WriteCapacityUnits: "1"
#      TableName: Student

  KonttiproggisCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: Konttiproggis-klusteri
      Tags:
        - Key: Owner
          Value: Kati

  KonttiproggisTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      RequiresCompatibilities:
        - FARGATE
      Cpu: 256
      Memory: 512
      ExecutionRoleArn: !Ref TaskExecutionRoleForTaskDefinition
      TaskRoleArn: !Ref TaskRoleForTaskDefinition
      ContainerDefinitions:
        - Name: !Ref ServiceName
          Image: !Ref DockerImage
          PortMappings:
            - ContainerPort: !Ref ContainerPort
      Family: konttiproggis-task
      # awsvpc is required for Fargate
      NetworkMode: awsvpc
      Tags:
        - Key: Owner
          Value: Kati

  KonttiproggisService:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: !Ref ServiceName
      Cluster: !Ref KonttiproggisCluster
      TaskDefinition: !Ref KonttiproggisTaskDefinition
      DeploymentConfiguration:
        MinimumHealthyPercent: 0
        MaximumPercent: 200
      DesiredCount: 1
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets:
            - !Ref SubnetA
            - !Ref SubnetB
          SecurityGroups:
            - !Ref ServiceSecurityGroup

  ServiceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: ServiceSecurityGroup
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: !Ref ContainerPort
          ToPort: !Ref ContainerPort
          CidrIp: 0.0.0.0/0

